version: "3.9"
services:
  app:
    build:
      context: .
    container_name: todo-api
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - internal

networks:
  internal:
    external: true